//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Version32
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise()
        {
            this.Durations = new HashSet<Duration>();
        }
    
        public int ExID { get; set; }
        public string ExName { get; set; }
        public string ExDesc { get; set; }
        public byte[] ExPic1 { get; set; }
        public byte[] ExPic2 { get; set; }
        public byte[] ExPic3 { get; set; }
        public byte[] ExPic4 { get; set; }
        public byte[] ExVid { get; set; }
        public int RxID { get; set; }
        public int DurID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duration> Durations { get; set; }
        public virtual RX RX { get; set; }
    }
}
